### ISSUE TITLE
Crashes immediately (was working before)

### ISSUE THREAD

**Issue by anirudhgarg** [tal952/NotionQuick#2]
Hey - this app was a godsend until it suddenly stopped working. Now it crashes immediately on launch. Any ideas on how to debug ? Maybe I changed something on my phone.

**Comment by tal952** [comment]
It's not working for me also, I'm working on a fix

**Comment by tal952** [comment]
@anirudhgarg Fixed, please update the APK :)

**Comment by anirudhgarg** [comment]
Great, thanks for the quick fix. It works now :) I was also about to tell you that if I tried to share  http://about:blank with the Notion sharing option it says that this is not supported. Looks like just changing that made it work. Thanks again 👍
