### ISSUE TITLE
App keeps stopping on Oneplus 6T OxygenOS

### ISSUE THREAD

**Issue by sambasivapentyala** [tal952/NotionQuick#3]
I have installed the app but I'm not able to open it. 

<img width="210" alt="Screenshot 2020-08-31 at 10 15 34 PM" src="https://user-images.githubusercontent.com/9838752/91744711-8039f780-ebd7-11ea-9dad-907d523b1b6d.png">

**Comment by tal952** [comment]
Hey, a few questions:
1. Do You Have The Notion app installed?
2. Did You update the NotionQuick app to 1.2?

Can You please verify the version of NotionQuick app by reinstalling the app

**Comment by sambasivapentyala** [comment]
Yes, I have the Notion app installed. And NotionQuick APK version is 1.2.

**Comment by sambasivapentyala** [comment]
I don't know whether they are related or not. Posting it just in case. But with a recent Chrome update, [notion quick add](https://barav.co/notion-quick-add/) stopped working. You can refer to the reddit thread [here](https://www.reddit.com/r/Notion/comments/idixwn/notion_quick_add_stopped_working/).

**Comment by tal952** [comment]
Can You please try to debug it? I didn't put any logs recording in the app. If there any way You can send here the exception You are getting it would be great

**Comment by sambasivapentyala** [comment]
I have tried to log using android bug tracking feature. Adding some lines of those logs which might help.

> 09-02 13:08:39.732  1000  1307  1307 W Looper  : Drained
09-02 13:08:40.144  1000  1307  4113 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=tal952.notionquick cmp=tal952.notionquick/.MainActivity} from uid 10049 pid 22170
09-02 13:08:40.171  1000  1307  1307 V SettingsProvider: Notifying for 0: content://settings/secure/reminder_exp_learning_time_elapsed
09-02 13:08:40.172  1000  1307  1398 D OpRestartProcessManager: updateSelf :  tal952.notionquick, size : 30
09-02 13:08:40.199  1000  1307  1414 I ActivityManager: Start proc 22429:tal952.notionquick/u0a144 for activity {tal952.notionquick/tal952.notionquick.MainActivity}
09-02 13:08:40.221  1000  1307  1345 D OnePlusSmartBoostManager: writeHotCount tal952.notionquick, pid=22429
09-02 13:08:40.221  1000  1307  1441 E OPPerf  : Exception : file not exits :/proc/22429/main_boost_switch
09-02 13:08:40.221  1000  1307  1441 E OPPerf  : Exception : file not exits :/proc/1307/main_boost_switch
09-02 13:08:40.227  1000  1307  1345 D OemSceneModeActivityStack: [scene] evaluateGameModes :  gameMsg.arg1=0 gameMsg.arg2=1
09-02 13:08:40.228  1000  1307  1345 D OpQuickReply: setQuickReplyResumed focusedApp AppWindowToken{9b47819 token=Token{2fafb60 ActivityRecord{69df363 u0 tal952.notionquick/.MainActivity t18606}}} pkgName tal952.notionquick
09-02 13:08:40.248  1000  1307  1398 D Foreground_io: TOP_APP is ProcessRecord{ea27b53 22429:tal952.notionquick/u0a144} uid is 10144
09-02 13:08:40.251  1000  1307 22454 D Foreground_io: Setting fg uid
09-02 13:08:40.252  1000  1307 22454 D Foreground_io: Done
09-02 13:08:40.281  1000  1307  4113 I ActivityTaskManager: START u0 {act=android.intent.action.SEND typ=text/plain flg=0x1 cmp=notion.id/notion.local.id.externalsharing.ExternalSharingActivity clip={text/plain T:https://tal952.github.io/NotionQuick/} (has extras)} from uid 10144 pid 22429
09-02 13:08:40.283 10144 22429 22429 E AndroidRuntime: FATAL EXCEPTION: main
09-02 13:08:40.283 10144 22429 22429 E AndroidRuntime: Process: tal952.notionquick, PID: 22429
09-02 13:08:40.283 10144 22429 22429 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{tal952.notionquick/tal952.notionquick.MainActivity}: android.content.ActivityNotFoundException: Unable to find explicit activity class {notion.id/notion.local.id.externalsharing.ExternalSharingActivity}; have you declared this activity in your AndroidManifest.xml?
09-02 13:08:40.283 10144 22429 22429 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3374)
09-02 13:08:40.283 10144 22429 22429 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3513)
09-02 13:08:40.283 10144 22429 22429 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
09-02 13:08:40.283 10144 22429 22429 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
09-02 13:08:40.283 10144 22429 22429 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
09-02 13:08:40.283 10144 22429 22429 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2109)
09-02 13:08:40.283 10144 22429 22429 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
09-02 13:08:40.283 10144 22429 22429 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
09-02 13:08:40.283 10144 22429 22429 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7682)
09-02 13:08:40.283 10144 22429 22429 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-02 13:08:40.283 10144 22429 22429 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
09-02 13:08:40.283 10144 22429 22429 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
09-02 13:08:40.283 10144 22429 22429 E AndroidRuntime: Caused by: android.content.ActivityNotFoundException: Unable to find explicit activity class {notion.id/notion.local.id.externalsharing.ExternalSharingActivity}; have you declared this activity in your AndroidManifest.xml?
09-02 13:08:40.283 10144 22429 22429 E AndroidRuntime: 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2239)
09-02 13:08:40.283 10144 22429 22429 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1895)
09-02 13:08:40.283 10144 22429 22429 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:5205)
09-02 13:08:40.283 10144 22429 22429 E AndroidRuntime: 	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:767)
09-02 13:08:40.283 10144 22429 22429 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:5163)
09-02 13:08:40.283 10144 22429 22429 E AndroidRuntime: 	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:754)
09-02 13:08:40.283 10144 22429 22429 E AndroidRuntime: 	at android.app.Activity.startActivity(Activity.java:5534)
09-02 13:08:40.283 10144 22429 22429 E AndroidRuntime: 	at android.app.Activity.startActivity(Activity.java:5502)
09-02 13:08:40.283 10144 22429 22429 E AndroidRuntime: 	at tal952.notionquick.MainActivity.onCreate(MainActivity.java:18)
09-02 13:08:40.283 10144 22429 22429 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7815)
09-02 13:08:40.283 10144 22429 22429 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7804)
09-02 13:08:40.283 10144 22429 22429 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1318)
09-02 13:08:40.283 10144 22429 22429 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3349)
09-02 13:08:40.283 10144 22429 22429 E AndroidRuntime: 	... 11 more
09-02 13:08:40.286  1000  1307 22459 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
09-02 13:08:40.293  1000  1307  2586 W ActivityTaskManager:   Force finishing activity tal952.notionquick/.MainActivity
09-02 13:08:40.295  1000  1307 22459 D DropBoxManagerService: Copy /data/system/dropbox/data_app_crash@2020-09-02-13_08_40_293.txt to /data/oem_log/
09-02 13:08:40.295  1000  1307  2586 D OpQuickReply: setQuickReplyResumed focusedApp AppWindowToken{bfd11d8 token=Token{bc8f8bb ActivityRecord{838714a u0 com.google.android.packageinstaller/com.android.packageinstaller.DeleteStagedFileOnResult t18605}}} pkgName com.google.android.packageinstaller
09-02 13:08:40.303  1000  1307  1398 D OpRestartProcessManager: Duration is too short, ignore : 125 in tal952.notionquick
09-02 13:08:40.303  1000  1307  1413 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
09-02 13:08:40.303  1000  1307  1413 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
09-02 13:08:40.303  1000  1307  1413 D Foreground_io: TOP_APP is ProcessRecord{200c77 22170:com.google.android.packageinstaller/u0a49} uid is 10049
09-02 13:08:40.304  1000  1307 22460 D Foreground_io: Setting fg uid
09-02 13:08:40.304  1000  1307 22460 D Foreground_io: Done
09-02 13:08:40.312  1000  1307  1412 I RoleUserState: Wrote roles.xml successfully
09-02 13:08:40.330  1000  1307 12553 I ActivityManager: Process tal952.notionquick (pid 22429) has died: vis TOP 
09-02 13:08:40.335  1000  1307 12553 D OemSceneModeActivityStack: [scene] evaluateGameModes :  gameMsg.arg1=0 gameMsg.arg2=1
09-02 13:08:40.335  1000  1307 12553 D OpQuickReply: setQuickReplyResumed focusedApp AppWindowToken{bfd11d8 token=Token{bc8f8bb ActivityRecord{838714a u0 com.google.android.packageinstaller/com.android.packageinstaller.DeleteStagedFileOnResult t18605}}} pkgName com.google.android.packageinstaller
09-02 13:08:40.336  1000  1307 12553 V ActivityTaskManager: GestureButton: skip computeBounds for this=ActivityRecord{d389fc4 u0 com.oneplus.filemanager/.classification.ClassificationActivity t18605} maxAspectRatio=0.0
09-02 13:08:40.336  1000  1307 12553 I chatty  : uid=1000(system) Binder:1307_1E identical 1 line
09-02 13:08:40.337  1000  1307 12553 V ActivityTaskManager: GestureButton: skip computeBounds for this=ActivityRecord{d389fc4 u0 com.oneplus.filemanager/.classification.ClassificationActivity t18605} maxAspectRatio=0.0
09-02 13:08:40.345  1000  1307  1878 D OemSceneModeActivityStack: [scene] evaluateGameModes :  gameMsg.arg1=0 gameMsg.arg2=1
09-02 13:08:40.346  1000  1307  1878 D OpQuickReply: setQuickReplyResumed focusedApp AppWindowToken{23985e2 token=Token{761eead ActivityRecord{d389fc4 u0 com.oneplus.filemanager/.classification.ClassificationActivity t18605}}} pkgName com.oneplus.filemanager
09-02 13:08:40.346  1000  1307  1878 V ActivityTaskManager: GestureButton: skip computeBounds for this=ActivityRecord{d389fc4 u0 com.oneplus.filemanager/.classification.ClassificationActivity t18605} maxAspectRatio=0.0
09-02 13:08:40.347  1000  1307  1878 I chatty  : uid=1000(system) Binder:1307_5 identical 1 line
09-02 13:08:40.347  1000  1307  1878 V ActivityTaskManager: GestureButton: skip computeBounds for this=ActivityRecord{d389fc4 u0 com.oneplus.filemanager/.classification.ClassificationActivity t18605} maxAspectRatio=0.0
09-02 13:08:40.356  1000  1307  1345 D Foreground_io: TOP_APP is ProcessRecord{f132814 21959:com.oneplus.filemanager/1000} uid is 1000
09-02 13:08:40.357  1000  1307 22463 D Foreground_io: Setting fg uid
09-02 13:08:40.357  1000  1307 22463 D Foreground_io: Done
09-02 13:08:40.378  1000  1307  1398 D OpRestartProcessManager: updateSelf :  com.oneplus.filemanager, size : 30
09-02 13:08:40.380  1000  1307 12553 V ActivityTaskManager: GestureButton: skip computeBounds for this=ActivityRecord{d389fc4 u0 com.oneplus.filemanager/.classification.ClassificationActivity t18605} maxAspectRatio=0.0
09-02 13:08:40.416  1000  1307  2586 I DropBoxManagerService: add tag=platform_stats_bookmark isTagEnabled=true flags=0x2
09-02 13:08:40.422  1000  1307  2586 D DropBoxManagerService: Copy /data/system/dropbox/platform_stats_bookmark@2020-09-02-13_08_40_421.txt to /data/oem_log/
09-02 13:08:40.424  1000  1307  1413 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
09-02 13:08:40.425  1000  1307  1413 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
09-02 13:08:40.795  1000  1307  1398 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{69df363 u0 tal952.notionquick/.MainActivity t-1 f}
09-02 13:08:40.796  1000  1307  1442 E OnePlusSmartBoostManager: Exception : file not exits :/proc/22429/memplus_type
09-02 13:08:40.846  1000  1307  1398 V ActivityTaskManager: GestureButton: skip computeBounds for this=ActivityRecord{d389fc4 u0 com.oneplus.filemanager/.classification.ClassificationActivity t18605} maxAspectRatio=0.0

**Comment by tal952** [comment]
Could you please update your Notion app and try again?

if it doesn't work, can you please:
1. go to a site in chrome.
2. share the site with Notion.

Did it work?

**Comment by sambasivapentyala** [comment]
I have updated the Notion app and now NotionQuick is working 👍

**Comment by tal952** [comment]
Awesome!
Sorry it took me so long to answer
