### ISSUE TITLE
Status bar icon

### ISSUE THREAD

**Issue by gbdematos** [tal952/NotionQuick#5]
Hi! Thanks for your awesome work, this app helps a lot using Notion.

Would it possible to add an icon to quick launch the app in the status bar, like Todoist in the image below? 

![Captura de tela 2020-11-02 171406](https://user-images.githubusercontent.com/3527479/97914572-db4eae80-1d2e-11eb-8fab-6200d57b2c64.png)

Thanks!

**Comment by tal952** [comment]
Hey, happy to hear that!

Well, I guess that is possible.
I just put the app on the main wall, so I don't really see it as valuable for me, but it's really a personal preference.

You are more than welcome to introduce a PR :)
