### ISSUE TITLE
Saving Image instead of URL

### ISSUE THREAD

**Issue by Dunxter** [tal952/NotionQuick#9]
I'm aware the web clipper tool on mobile allows the user to create a page from an image, instead of a URL (saved inside the page content). I was wondering if this tool could make use of that functionality, and maybe find a way to use a "blank" image that doesn't load up in the page (or something similar, just to avoid saving the URL property). I'm not very knowledgeable about this, so I hope you can help me get a better understanding of how this works.

Many thanks! This tool is really useful, great job :)

**Comment by tal952** [comment]
Hey, happy you find value in the tool :)
For me, the extra URL property gives me an extra data, so I can know where this record came from (If I'm using notion directly, the URL is empty).
But you can open a PR and lets discuss this 👍
